version: "3"
services:
  db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck: 
      test: 
        - "CMD-SHELL"
        -  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      timeout: "45s"
      interval: "2s"
      retries: 10
    volumes:
      - postgres:/var/lib/postgresql/data
  migrate:
    build:
      context: .
    entrypoint: sh
    command: -c "./DbMigrationsBundle --connection $$MIGRATION_CONNECTION"
    environment:
      MIGRATION_CONNECTION: Host=db:5432;Username=admin;Password=admin;Database=postgres
    depends_on:
      db: 
        condition: "service_healthy"
  server:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      ASPNETCORE_HTTP_PORTS: ${PORT}
      ConnectionStrings__DbContext: Host=db:5432;Username=admin;Password=admin;Database=postgres
    restart: on-failure
    depends_on:
      migrate:
        condition: "service_completed_successfully"
    profiles:
      - complete
volumes:
  postgres: ~
